import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "@/css/global.css";
import Header from "@/components/global/header";
import Footer from "@/components/global/footer";
import { CurrencyProvider } from "@/context/CurrencyContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Kular Fashion",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <CurrencyProvider>
          <Header />
          {children}
          <Footer />
        </CurrencyProvider>
      </body>
    </html>
  );
}
